-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 14:37:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`branches` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(100) NULL,
  `branch_phone` VARCHAR(20) NULL,
  `branch_address` VARCHAR(100) NULL,
  `branch_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NULL,
  `user_password` VARCHAR(255) NULL,
  `user_role` ENUM('Super Admin', 'Admin', 'User') NULL,
  `user_full_name` VARCHAR(255) NULL,
  `user_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `branch_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_branches_idx` (`branch_id` ASC),
  CONSTRAINT `fk_users_branches`
    FOREIGN KEY (`branch_id`)
    REFERENCES `inventory`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`distributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`distributors` (
  `distributor_id` INT NOT NULL AUTO_INCREMENT,
  `distributor_name` VARCHAR(45) NULL,
  `distributor_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `distributor_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`distributor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NULL,
  `item_sku` VARCHAR(45) NULL,
  `item_merk` VARCHAR(45) NULL,
  `item_price` DECIMAL NULL,
  `item_stock` INT NULL,
  `item_image` VARCHAR(255) NULL,
  `distributor_id` INT NULL,
  `item_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `item_updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_distributors1_idx` (`distributor_id` ASC),
  CONSTRAINT `fk_items_distributors1`
    FOREIGN KEY (`distributor_id`)
    REFERENCES `inventory`.`distributors` (`distributor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`stocks` (
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  `stock_no_trx` VARCHAR(45) NULL,
  `user_id` INT NULL,
  `stock_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`stock_id`),
  INDEX `fk_stocks_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_stocks_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventory`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`stock_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`stock_details` (
  `stock_id` INT NULL,
  `item_id` INT NULL,
  `qty` INT NULL,
  INDEX `fk_stock_details_stocks1_idx` (`stock_id` ASC),
  INDEX `fk_stock_details_items1_idx` (`item_id` ASC),
  CONSTRAINT `fk_stock_details_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `inventory`.`stocks` (`stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_details_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `inventory`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`mutations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`mutations` (
  `mutation_id` INT NOT NULL AUTO_INCREMENT,
  `mutation_no_trx` VARCHAR(45) NULL,
  `branch_id` INT NULL,
  `user_id` INT NULL,
  `mutation_user_approve` INT NULL,
  `mutation_status` TINYINT NULL DEFAULT 0,
  `mutation_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `mutation_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`mutation_id`),
  INDEX `fk_mutations_branches1_idx` (`branch_id` ASC),
  INDEX `fk_mutations_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_mutations_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `inventory`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventory`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`mutation_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`mutation_details` (
  `mutation_id` INT NULL,
  `item_id` INT NULL,
  `qty` INT NULL,
  INDEX `fk_mutation_details_mutations1_idx` (`mutation_id` ASC),
  INDEX `fk_mutation_details_items1_idx` (`item_id` ASC),
  CONSTRAINT `fk_mutation_details_mutations1`
    FOREIGN KEY (`mutation_id`)
    REFERENCES `inventory`.`mutations` (`mutation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutation_details_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `inventory`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`item_branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`item_branch` (
  `item_branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NULL,
  `item_id` INT NULL,
  `item_branch_stock` INT NULL,
  `item_branch_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `item_branch_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_item_branch_branches1_idx` (`branch_id` ASC),
  INDEX `fk_item_branch_items1_idx` (`item_id` ASC),
  PRIMARY KEY (`item_branch_id`),
  CONSTRAINT `fk_item_branch_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `inventory`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_branch_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `inventory`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_no_trx` VARCHAR(45) NULL COMMENT '		',
  `transaction_total_price` DECIMAL NULL,
  `user_id` INT NULL,
  `branch_id` INT NULL,
  `transaction_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `transaction_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_transactions_users1_idx` (`user_id` ASC),
  INDEX `fk_transactions_branches1_idx` (`branch_id` ASC),
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventory`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `inventory`.`branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`transaction_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`transaction_details` (
  `transaction_id` INT NULL,
  `item_branch_id` INT NULL,
  `qty` INT NULL,
  `item_price` DECIMAL NULL,
  INDEX `fk_transaction_details_transactions1_idx` (`transaction_id` ASC),
  INDEX `fk_transaction_details_item_branch1_idx` (`item_branch_id` ASC),
  CONSTRAINT `fk_transaction_details_transactions1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `inventory`.`transactions` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_details_item_branch1`
    FOREIGN KEY (`item_branch_id`)
    REFERENCES `inventory`.`item_branch` (`item_branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
