-- MySQL Script generated by MySQL Workbench
-- Kam 21 Mar 2019 02:14:42  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `branches` (
  `branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(100) NULL,
  `branch_phone` VARCHAR(20) NULL,
  `branch_address` VARCHAR(100) NULL,
  `branch_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`branch_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NULL,
  `user_password` VARCHAR(255) NULL,
  `user_role` ENUM('Super Admin', 'Admin', 'User') NULL,
  `user_full_name` VARCHAR(255) NULL,
  `user_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `branch_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_branches_idx` (`branch_id` ASC),
  CONSTRAINT `fk_users_branches`
    FOREIGN KEY (`branch_id`)
    REFERENCES `branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distributors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distributors` (
  `distributor_id` INT NOT NULL AUTO_INCREMENT,
  `distributor_name` VARCHAR(45) NULL,
  `distributor_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `distributor_updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`distributor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(100) NULL,
  `item_sku` VARCHAR(45) NULL,
  `item_merk` VARCHAR(45) NULL,
  `item_price` DECIMAL NULL,
  `item_stock` INT NULL,
  `item_image` VARCHAR(255) NULL,
  `branch_id` INT NULL,
  `distributor_id` INT NULL,
  `item_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `item_updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_branches1_idx` (`branch_id` ASC),
  INDEX `fk_items_distributors1_idx` (`distributor_id` ASC),
  CONSTRAINT `fk_items_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_distributors1`
    FOREIGN KEY (`distributor_id`)
    REFERENCES `distributors` (`distributor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mutations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mutations` (
  `mutation_id` INT NOT NULL AUTO_INCREMENT,
  `mutation_no` VARCHAR(45) NULL,
  `branch_id` INT NULL,
  `item_id` INT NULL,
  `user_id` INT NULL,
  `mutation_status` TINYINT NULL DEFAULT 0,
  `mutation_created_at` TIMESTAMP NULL,
  PRIMARY KEY (`mutation_id`),
  INDEX `fk_mutations_items1_idx` (`item_id` ASC),
  INDEX `fk_mutations_branches1_idx` (`branch_id` ASC),
  INDEX `fk_mutations_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_mutations_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutations_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mutations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stocks` (
  `stock_id` INT NOT NULL AUTO_INCREMENT,
  `stock_no_trx` VARCHAR(45) NULL,
  `branch_id` INT NULL,
  `user_id` INT NULL,
  `stock_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`stock_id`),
  INDEX `fk_stocks_branches1_idx` (`branch_id` ASC),
  INDEX `fk_stocks_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_stocks_branches1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `branches` (`branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stocks_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_details` (
  `stock_id` INT NULL,
  `item_id` INT NULL,
  `qty` INT NULL,
  INDEX `fk_stock_details_stocks1_idx` (`stock_id` ASC),
  INDEX `fk_stock_details_items1_idx` (`item_id` ASC),
  CONSTRAINT `fk_stock_details_stocks1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `stocks` (`stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_details_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
